### ISSUE TITLE
No resource, method, or local variable named `service_group' for `Chef::Recipe "package"'

### ISSUE THREAD

**Issue by livewyer** [chef-cookbooks/memcached#60]
Included memcached recipe in project recipe, used berks to gather dependencies.  

```
NameError
 ---------
 No resource, method, or local variable named `service_group' for `Chef::Recipe "package"'
 
 Cookbook Trace:
 ---------------
   /tmp/vagrant-chef/5c78b9cb779c90c4a149b7577fc0e343/cookbooks/memcached/recipes/package.rb:50:in `from_file'
   /tmp/vagrant-chef/5c78b9cb779c90c4a149b7577fc0e343/cookbooks/memcached/recipes/default.rb:20:in `from_file'
   /tmp/vagrant-chef/5c78b9cb779c90c4a149b7577fc0e343/cookbooks/project/recipes/default.rb:24:in `from_file'
 
 Relevant File Content:
 ----------------------
 /tmp/vagrant-chef/5c78b9cb779c90c4a149b7577fc0e343/cookbooks/memcached/recipes/package.rb:
 
  43:  else
  44:    package 'memcached' do
  45:      version node['memcached']['version']
  46:      action :install
  47:    end
  48:  end
  49:  
  50>> group service_group do
  51:    system true
  52:    notifies :create, "user[#{service_user}]", :immediately
  53:    notifies :lock, "user[#{service_user}]", :immediately
  54:    not_if "getent passwd #{service_user}"
  55:  end
  56:  
  57:  user service_user do
 
  58:    system true
  59:    manage_home false
```

Contents of Chef stacktrace: 
```
Generated at 2016-01-28 23:03:58 +0000
NameError: No resource, method, or local variable named `service_group' for `Chef::Recipe "package"'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/dsl/recipe.rb:104:in `rescue in method_missing'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/dsl/recipe.rb:99:in `method_missing'
/tmp/vagrant-chef/5c78b9cb779c90c4a149b7577fc0e343/cookbooks/memcached/recipes/package.rb:50:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/cookbook_version.rb:229:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:333:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:288:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:287:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:287:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/tmp/vagrant-chef/5c78b9cb779c90c4a149b7577fc0e343/cookbooks/memcached/recipes/default.rb:20:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/cookbook_version.rb:229:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:333:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:288:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:287:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:287:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/tmp/vagrant-chef/5c78b9cb779c90c4a149b7577fc0e343/cookbooks/project/recipes/default.rb:24:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/cookbook_version.rb:229:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:333:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/run_context.rb:167:in `load'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/policy_builder/expand_node_object.rb:93:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:490:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:268:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:203:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/solo.rb:286:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/solo.rb:275:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/solo.rb:275:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/solo.rb:253:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-solo:25:in `<top (required)>'
/bin/chef-solo:54:in `load'
/bin/chef-solo:54:in `<main>'
```

This was tested inside a CentOS7 vagrant, Ubuntu 14.04 host.

**Comment by tas50** [comment]
What version of chef is this occurring with?

**Comment by livewyer** [comment]
```bash
$ chef -v
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

**Comment by tas50** [comment]
Any chance you can try out the lastest cookbook on Chef 12.8.1.  It seems like chef-solo is skipping over the libraries directory for some reason.  I know we've changed how that works a bit in 12.8 so perhaps we resolved this issue.

**Comment by livewyer** [comment]
Sure thing. Can't promise it'll be right away. We worked around the problem by adapting parts of this cookbook to our needs. Whatever we needed was unrelated to the bug and I wasn't sure how/where to investigate.

On March 16, 2016 10:56:10 PM CDT, Tim Smith <notifications@github.com> wrote:
>Any chance you can try out the lastest cookbook on Chef 12.8.1.  It
>seems like chef-solo is skipping over the libraries directory for some
>reason.  I know we've changed how that works a bit in 12.8 so perhaps
>we resolved this issue.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chef-cookbooks/memcached/issues/60#issuecomment-197681935

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tas50** [comment]
This should be resolved with the refactoring
