### ISSUE TITLE
Fix Debian 7 init script

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/memcached#72]
The current init script only works on RHEL.  We need a universal script that supports both LSB implementations.

**Comment by pavel-d** [comment]
+1

I'm getting this on Debian 7 on the latest version of this cookbook

```
==> default: ================================================================================
==> default:       
==> default: Error executing action `start` on resource 'service[memcached]'
==> default:       
==> default: ================================================================================
==> default:       
==> default: 
==> default: 
==> default:       
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default:       
==> default: ------------------------------------
==> default:       
==> default: Expected process to exit with [0], but received '1'
==> default: 
==> default:       
==> default: ---- Begin output of /etc/init.d/memcached start ----
==> default: 
==> default:       
==> default: STDOUT: 
==> default: 
==> default:       
==> default: STDERR: /etc/init.d/memcached: line 22: /etc/rc.d/init.d/functions: No such file or directory
==> default: 
==> default:       ---- End output of /etc/init.d/memcached start ----
==> default:       Ran /etc/init.d/memcached start returned 1
==> default:       
==> default:       Cookbook Trace:
==> default:       ---------------
==> default:       /tmp/vagrant-chef/ae950b20603ec128ad137dbb75e8f9a3/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
==> default:       /tmp/vagrant-chef/ae950b20603ec128ad137dbb75e8f9a3/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:125:in `compile_and_converge_action'
==> default:       /tmp/vagrant-chef/ae950b20603ec128ad137dbb75e8f9a3/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
==> default:       
==> default:       Resource Declaration:
==> default:       ---------------------
==> default:       # In /tmp/vagrant-chef/ae950b20603ec128ad137dbb75e8f9a3/cookbooks/memcached/resources/instance_sysv_init.rb
==> default:       
==> default:        50:   service memcached_instance_name do
==> default:        51:     supports restart: true, status: true
==> default:        52:     action :start
==> default:        53:   end
==> default:        54: end
==> default:       
==> default:       Compiled Resource:
==> default:       ------------------
==> default:       # Declared in /tmp/vagrant-chef/ae950b20603ec128ad137dbb75e8f9a3/cookbooks/memcached/resources/instance_sysv_init.rb:50:in `block in class_from_file'
==> default:       
==> default:       service("memcached") do
==> default:         action [:start]
==> default:         supports {:restart=>true, :status=>true}
==> default:         retries 0
==> default:         retry_delay 2
==> default:         default_guard_interpreter :default
==> default:         service_name "memcached"
==> default:         pattern "memcached"
==> default:         declared_type :service
==> default:         cookbook_name :memcached
==> default:       end
==> default:       
==> default:       Platform:
==> default:       ---------
==> default:       x86_64-linux
==> default:       
==> default: [2016-05-27T09:33:42+00:00] INFO: Running queued delayed notifications before re-raising exception
```

**Comment by koertkuipers** [comment]
it actually doesnt work on centos either

**Comment by fletchowns** [comment]
Are there any workarounds?

**Comment by tas50** [comment]
I've included a init script that works on Debian now. There's still some rough edges and I'm trying to get to the point where the instances tests pass on every platform, but it's there and will be released pretty soon.
